### ISSUE TITLE
Publish to pub.dartlang.org

### ISSUE THREAD

**Issue by ichigotake** [danellis/dart-msgpack#1]
I want to use this library.

But it does not publishing to [https://pub.dartlang.org/](https://pub.dartlang.org/) now.

Please publish to use `pub` :)

**Comment by bipin-nag** [comment]
+1 Please publish it.

Also list the package in msgpack list at msgpack.org, see : https://github.com/msgpack/website/blob/master/README.md

**Comment by danellis** [comment]
Unfortunately, it's not quite ready to publish yet. Although it works for me, it doesn't have any way to generate message classes. I'm still deciding whether to have a script to generate them from the MessagePack IDL or to use reflection at runtime. I currently have hand-written classes that look like this:

``` dart
class ServerHelloFrame extends Message {
    String server;
    String talkerName;
    Map<String, String> commands;
    Map<String, String> templates;
    String username;

    ServerHelloFrame(this.server, this.talkerName, this.commands, this.templates, this.username);

    static ServerHelloFrame fromList(List f) => new ServerHelloFrame(f[0], f[1], f[2], f[3], f[4]);
    List toList() => [server, talkerName, commands, templates, username];
}
```

If you desperately wanted to use it like that (and I understand that there aren't any other options right now), you can always include the git URL in your pubspec.

**Comment by ichigotake** [comment]
> you can always include the git URL in your pubspec.

I know this spec. 

But we show library presence for people with publish to pub.dartlang.org . 

We should publish as better.

> I'm still deciding whether to have a script to generate them from the MessagePack IDL or to use reflection at runtime. 

I think, refrection is heavy at runtime. But still comparing benchmarks.

If possible to avoid refrection, it's so better for me.

**Comment by bipin-nag** [comment]
I agree that IDL is the better route. But still that maybe overkill, the IDL won't change frequently. Writing class generator may not be that benficial. For now just adding pack, unpack would be a start, say v0.0.1. That can be added later. Also it will ease you into writing the generator.

Besides dart has a variety of datatypes that map cleanly. So writing a script for generating class from IDL won't be that difficult.

**Comment by ichigotake** [comment]
> For now just adding pack, unpack would be a start, say v0.0.1.

:+1:

**Comment by danellis** [comment]
Alright, I've added a brief readme and published to pub. Improvements welcomed, of course.

**Comment by ichigotake** [comment]
Great, thanks!

I will help you.
