### ISSUE TITLE
Is it good for serious use?

### ISSUE THREAD

**Issue by oxysoft** [danellis/dart-msgpack#3]
I am interested in using MessagePack for a serious project. Is this library feature complete and does it perform well?

Thanks

**Comment by azenla** [comment]
Hi. @danellis, if you are not going to continue this library, I would like to continue it. I've implemented the entire MsgPack spec in a fast efficient way, and would like to take control of this library.

**Comment by danellis** [comment]
Yes, please do. As far as I know, Dart is still lacking a good MsgPack library. What do you need from me to take ownership on pub.dartlang.org?

**Comment by azenla** [comment]
@danellis You can do the following :)

```
pub uploader add kaendfinger@gmail.com --package=msgpack
```

**Comment by danellis** [comment]
Done
